[workspace]
resolver = "2"
exclude = ["contracts"]


members = [
	"pallets/registry",
	"pallets/oracle",
	"node",
	"runtime/paraxiom",
]


[profile.release]
panic = "unwind"
opt-level = 3

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
