[relaychain]

default_command = "../polkadot/target/release/polkadot"
# default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true


[[parachains]]
id = 100
cumulus_based = true
 [[parachains.collators]]
name = "node2"
command = "./target/release/paraxiom"

 [[parachains.collators]]
name = "node1"
command = "./target/release/paraxiom"
