[workspace]
members = [
    "crates/rollup",
    "contracts/local_scheduler",
    "contracts/sub0_factory",
    "contracts/sub_price_feed",
    "contracts/evm_price_feed",
]

# Sneak peek of the new test engine!
[patch.crates-io]
ink_primitives = { git = "https://github.com/Phala-Network/ink.git", branch = "advtest-3.4.0" }
ink_metadata = { git = "https://github.com/Phala-Network/ink.git", branch = "advtest-3.4.0" }
ink_env = { git = "https://github.com/Phala-Network/ink.git", branch = "advtest-3.4.0" }
ink_storage = { git = "https://github.com/Phala-Network/ink.git", branch = "advtest-3.4.0" }
ink_lang = { git = "https://github.com/Phala-Network/ink.git", branch = "advtest-3.4.0" }
ink_lang_codegen = { git = "https://github.com/Phala-Network/ink.git", branch = "advtest-3.4.0" }
ink_lang_ir = { git = "https://github.com/Phala-Network/ink.git", branch = "advtest-3.4.0" }
ink_lang_macro = { git = "https://github.com/Phala-Network/ink.git", branch = "advtest-3.4.0" }
serde = { git = "https://github.com/kvinwang/serde.git", branch = "pink" }