[package]
name = "pink-utils"
version = "0.4.0"
edition = "2021"
description = "Useful utilities for pink"
homepage = "https://github.com/Phala-Network/phala-blockchain"
license = "Apache-2.0"
keywords = ["fat-contract", "pink", "ink"]

[dependencies]
ink = { version = "4.0.0-rc", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }

pink-extension = { version = "0.4.0", default-features = false, path = "../../pink/pink-extension" }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }

[dev-dependencies]
pink-extension-runtime = { path = "../../pink/pink-extension-runtime" }

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    "pink-extension/std",
]
