[package]
authors = ["Phala Network"]
edition = "2021"
name = "phat-offchain-rollup"
version = "0.1.0"
license = "Apache 2.0"
homepage = "https://phala.network/"
repository = "https://github.com/Phala-Network/phala-blockchain"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1", default-features = false, features = ["derive", "max-encoded-len"] }
scale-info = { version = "2.1", default-features = false, features = ["derive"] }

primitive-types = { version = "0.12.1", default-features = false, features = ["codec", "byteorder"] }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33", default-features = false }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33", default-features = false, optional = true }
log = { version = "0.4.14", default-features = false }

hex = { version = "0.4", default-features = false }
hex-literal = "0.3.4"

[dev-dependencies]
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
frame-support-test = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
kv-session = { path = "../../crates/pink-libs/kv-session", package = "pink-kv-session" }
assert_matches = "1.4.0"

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-std/std",
	"sp-core/std",
	"sp-application-crypto/std",
	"frame-support/std",
	"frame-system/std",
	"frame-benchmarking/std",
	"log/std",
    "primitive-types/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks"
]
try-runtime = ["frame-support/try-runtime"]
