[relaychain]

default_command = "../../polkadot/target/release/polkadot"
# default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true


[[parachains]]
id = 100
cumulus_based = true
 [[parachains.collators]]
name = "node2"
command = "../target/release/paraxiom"
rpc_port = 30488


 [[parachains.collators]]
name = "node1"
command = "../target/release/paraxiom"
rpc_port = 30489

[[parachains]]
id = 200
cumulus_based = true
 [[parachains.collators]]
name = "node2"
command = "../target/release/paraxiom"
rpc_port = 30488


 [[parachains.collators]]
name = "node1"
command = "../target/release/paraxiom"
rpc_port = 30489
