[package]
edition = "2021"
name = "sidevm-host-runtime"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
dashmap = "5.2.0"
futures = "0.3"
hex_fmt = "0.3.0"
log = "0.4.16"
loupe = "0.1.3"
sidevm-env = { path = "../env", features = ["host"] }
thread_local = "1.1"
tokio = { version = "1.20.3", features = ["full"] }
wasmer = "3"
wasmer-wasi-types = "3"
wasmer-compiler-singlepass = "3"
wasmer-compiler-cranelift = { version = "3", optional = true }
wasmer-compiler-llvm = { version = "3", optional = true }
wasmer-tunables = { path = "../../wasmer-tunables" }
wasmer-middlewares = "3"
parity-wasm = "0.45.0"
wasm-instrument = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8.5"
thiserror = "1"
libc = "0.2"
scale = { version = "3.1", package = "parity-scale-codec" }
tokio-rustls = "0.23"
rustls-pemfile = "1"
webpki-roots = "0.22"
once_cell = "1"
tokio-proxy = { git  = "https://github.com/Phala-Network/tokio-proxy" }
page_size = "0.4.2"
phala-scheduler = { path = "../../phala-scheduler" }
derive_more = "0.99.17"
