name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install --assume-yes build-essential git clang curl libssl-dev protobuf-compiler
    - name: Build
      run: cargo +nightly clippy --verbose
    - name: Run tests
      run: cargo +nightly fmt --verbose
